version: "3.8"
# Compose file build variables set in .env
services:
  supervisor:
    build:
      context: ./build
      args:
        # Remove as appropriate
        IMAGE_BASE: ${IMAGE_BASE:-nvidia/cuda:12.1.0-base-ubuntu22.04}
        IMAGE_TAG: ${IMAGE_TAG:-cuda-12.1.0-base-22.04}
        XPU_TARGET: ${XPU_TARGET:-NVIDIA_GPU}
        CUDA_VERSION: ${CUDA_VERSION:-11.8.0}
        CUDA_LEVEL: ${CUDA_LEVEL:-base}
        CUDNN_VERSION: ${CUDNN_VERSION:-8}
        PYTHON_VERSION: ${PYTHON_VERSION:-all}
        PYTHON_MAMBA_NAME: ${PYTHON_MAMBA_NAME:-python_312}
      tags:
        - "ghcr.io/harshc/leonardo-base:${IMAGE_TAG:-py312-cuda-12.1.0-base-22.04}"
        
    image: ghcr.io/harshc/leonardo-base:${IMAGE_TAG:-py312-cuda-12.1.0-base-22.04}
    
    ## For Nvidia GPU's - You probably want to uncomment this
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
    
    
    devices:
      - "/dev/dri:/dev/dri"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"
      
    volumes:
      # Workspace
      - ./workspace:${WORKSPACE:-/workspace}:rshared
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./config/provisioning/default.sh:/opt/leonardo/bin/provisioning.sh
      
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - ${SSH_PORT_HOST:-2222}:22
        # Caddy port for service portal
        - ${SERVICEPORTAL_PORT_HOST:-1111}:${SERVICEPORTAL_PORT_HOST:-1111}

    environment:
        # Important: Edit values in .env - not here.
        # Don't enclose values in quotes
        - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
        - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
        - WORKSPACE=${WORKSPACE:-/workspace}
        - WORKSPACE_SYNC=${WORKSPACE_SYNC:-false}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS:-true}
        - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH:-true}
        - WEB_USER=${WEB_USER:-user}
        - WEB_PASSWORD=${WEB_PASSWORD:-password}
        - SERVERLESS=${SERVERLESS:-false}
        - SSH_PORT_HOST=${SSH_PORT_HOST:-2222}
        - SERVICEPORTAL_PORT_HOST=${SERVICEPORTAL_PORT_HOST:-1111}
        - SERVICEPORTAL_METRICS_PORT=${SERVICEPORTAL_METRICS_PORT:-21111}
        #- PROVISIONING_SCRIPT=https://raw.githubusercontent.com/leonardo/base-image/main/config/provisioning/default.sh
